name: PR Guard

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch is dev
        uses: actions/github-script@v7
        with:
          script: |
            const base = context.payload.pull_request.base.ref;
            const head = context.payload.pull_request.head.ref;
            if (base === 'main' && head !== 'dev') {
              core.setFailed(`Only PRs from 'dev' can be merged into 'main'. Received: ${head} -> ${base}`);
            }

