name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config

      - name: Install dependencies
        run: npm ci

      - name: Build workspace packages
        run: npm run build --workspace=packages/ui --workspace=packages/ingest --workspace=packages/localdb

      - name: Build the app
        run: cd apps/desktop && npm run tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasteday-${{ github.ref_name }}
          path: |
            apps/desktop/src-tauri/target/release/bundle/
            apps/desktop/src-tauri/target/release/wasteday.exe

  update-server:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasteday-${{ github.ref_name }}

      - name: Setup release server
        run: |
          # ここで実際のアップデートサーバーにファイルをアップロード
          # 例: AWS S3, GitHub Releases, または独自のサーバー
          echo "Uploading to update server..."
          # aws s3 sync . s3://releases.wasteday.app/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apps/desktop/src-tauri/target/release/bundle/msi/wasteday_*.msi
            apps/desktop/src-tauri/target/release/bundle/nsis/wasteday_*.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
