name: Release Build (tag)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build workspaces
        run: npm run build --workspaces

      - name: Upload desktop app dist
        uses: actions/upload-artifact@v4
        with:
          name: desktop-dist
          path: apps/desktop/dist
          if-no-files-found: ignore

      - name: Upload ui package dist
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: packages/ui/dist
          if-no-files-found: ignore

      - name: Upload database package dist
        uses: actions/upload-artifact@v4
        with:
          name: database-dist
          path: packages/database/dist
          if-no-files-found: ignore

      - name: Upload ingest package dist
        uses: actions/upload-artifact@v4
        with:
          name: ingest-dist
          path: packages/ingest/dist
          if-no-files-found: ignore

      - name: Upload localdb package dist
        uses: actions/upload-artifact@v4
        with:
          name: localdb-dist
          path: packages/localdb/dist
          if-no-files-found: ignore

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm ci

      - name: Build workspace packages
        run: npm run build --workspace=packages/ui --workspace=packages/ingest --workspace=packages/localdb

      - name: Build the app
        run: cd apps/desktop && npm run tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasteday-${{ github.ref_name }}
          path: apps/desktop/src-tauri/target/release/bundle/

  create-github-release:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasteday-${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.msi
            **/*.exe
            **/*.app
            **/*.dmg
            **/*.deb
            **/*.AppImage
            **/*.sig
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
